# Generated by Django 3.1.2 on 2020-10-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userlogin',
        ),
    ]
