# Generated by Django 3.1.2 on 2020-10-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201021_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='name',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='userlogin',
            old_name='password',
            new_name='username',
        ),
    ]
