# Generated by Django 3.1.2 on 2020-10-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201022_0056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userlogin',
        ),
    ]
